# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /restful-go-api

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /restful-go-api /restful-go-api

EXPOSE 8081

USER nonroot:nonroot

ENTRYPOINT ["/restful-go-api"]